name: ANZeducation
favicon: null
layout_spectrum: 0.6495441400911659
typography_spectrum: 0.05009806645102799
title: ANZ International Education
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5598286625463516
  lightness: 0.5034747235476971
  saturation: 0.949097762349993
  rhythmicContrast: 0.9840008693281561
purpose: []
